### PR TITLE
Add install from settings.jar

### PR DESCRIPTION
**Pull request by mstuttgart**
Some improvements in to install method:

* [NEW] Add `settings.jar* to install templates from PyCharm IDE `Import Settings` options.
* [NEW] Add `build-jar.sh` script to build `.jar` file.
* [IMP] Improve install instructions on README. 

**NOTE**: `settings.jar` download link work after this PR wiil be merged.

@mohamedmagdy can you take a look? :)

### CODE REVIEW

**Comment by mstuttgart** [comment]
@mohamedmagdy can you take a look? :)

**Comment by mohamedmagdy** [comment]
@mstuttgart , I really appreciate your work on the templates. It was really a good value to have.

Also, I would like to apologize for being late as I got very busy the last few days and I was not able to test your updates.

Thank you :+1:  :)

**Comment by mohamedmagdy** [comment]
@mstuttgart , I think it will be a great idea to explain the installation in a video. But it will be great if you have time to produce it. 

Thanks again :D

**Comment by mstuttgart** [comment]
No problem @mohamedmagdy :) This project is awesome and very useful to me and my team. :100: 

About the video, I am busy in this days but I will try produce it. :movie_camera: Thanks!

**Comment by mohamedmagdy** [comment]
I really appreciate your words and really happy to know that it helps you and your team :)

I will write a tweet on twitter about the updates but I want to mention you in the tweet, can you send me a link to your twitter account so that the followers can know who is the guy behind the updates?

Thank you again :)

**Comment by mstuttgart** [comment]
HI @mohamedmagdy i don't have a twitter account, sorry. But you can post link to my github profile: https://github.com/mstuttgart. :+1:

**Comment by mohamedmagdy** [comment]
Done :+1: 
https://twitter.com/Mo7amed_Ma9dy/status/920601470847913984

Thanks again :)

**Pull request merged**
